version: '3.8'
services:
  postgres:
    image: postgres:latest
    container_name: bdd_container
    environment:
      POSTGRES_USER: boris
      POSTGRES_PASSWORD: caroline
      POSTGRES_DB: match_up
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - postgres_network

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@gmail.com 
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8080:80"
    depends_on: 
      - postgres
    networks:
      - postgres_network

volumes:
  postgres_data:

networks:
  postgres_network:
    driver: bridge
